### ISSUE TITLE
detect.py运行出错

### ISSUE THREAD

**Issue by CVer2022** [qfs1980398040/yolo-v3-DarkNet53-MobileNet-V2-#1]
Traceback (most recent call last):
  File "D:/DeepLearning/PyCharmProjects/Yolo/detect.py", line 275, in <module>
    result=detector(_img_data, 0.2, anchors,case)
  File "D:\DeepLearning\Anconda3_2019.10\envs\Pytorch\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:/DeepLearning/PyCharmProjects/Yolo/detect.py", line 213, in forward
    boxes_13 = self._parse(idxs_13, vecs_13, 32, anchors[13],case)
  File "D:/DeepLearning/PyCharmProjects/Yolo/detect.py", line 257, in _parse
    cls_index = torch.argmax(cls_p, dim=1)
RuntimeError: cannot perform reduction function argmax on a tensor with no elements because the operation does not have an identity

**Comment by qiaofengsheng** [comment]
更新pytorch版本
低版本当argmax内部参数值为空会报错，更新最新pytorch或者你自己这个判断语句去做判空处理

**Comment by gjr2019** [comment]
> 更新pytorch版本
> 低版本当argmax内部参数值为空会报错，更新最新pytorch或者你自己这个判断语句去做判空处理

**Comment by CVer2022** [comment]
pytorch版本应该没问题，1.8版本
